language: ruby
cache: bundler
rvm:
  - 2.6.5
before_install:
  - gem update --system
  - gem install bundler
  - rake db:create
  - rake db:migrate
script:
  - bundle exec standardrb
  - xvfb-run bundle exec rspec
services:
  - postgresql
